
import { GoogleGenAI } from "@google/genai";
import { Activity, LessonPlan, SLO } from '../types';

/**
 * Parses the structured text response from the model into a LessonPlan object.
 * @param text The raw text from the Gemini API.
 * @param gradeLevel The grade level context for the lesson.
 * @param subject The subject for the lesson.
 * @returns A LessonPlan object.
 * @throws An error if parsing fails.
 */
function parseLessonPlanText(text: string, gradeLevel: string, subject: string): LessonPlan {
    const lessonPlan: LessonPlan = {
        title: '',
        objective: '',
        gradeLevel,
        subject,
        materials: [],
        activities: [],
        assessment: '',
        homework: '',
        summary: '',
    };

    try {
        const topicMatch = text.match(/LESSON TOPIC:([\s\S]*?)(LEARNING OBJECTIVES \(SLOs\):|$)/i);
        if (topicMatch) lessonPlan.title = topicMatch[1].trim();

        const objectiveMatch = text.match(/LEARNING OBJECTIVES \(SLOs\):([\s\S]*?)(RESOURCES:|$)/i);
        if (objectiveMatch) lessonPlan.objective = objectiveMatch[1].replace(/\(Students will be able to: \*\)/, '').trim();

        const resourcesMatch = text.match(/RESOURCES:([\s\S]*?)(LESSON PROCEDURE & TIMINGS|$)/i);
        if (resourcesMatch) {
            lessonPlan.materials = resourcesMatch[1].split('\n')
                .map(line => line.trim())
                .filter(line => line.startsWith('-'))
                .map(line => line.substring(1).trim())
                .filter(Boolean);
        }

        const activitiesTextMatch = text.match(/LESSON PROCEDURE & TIMINGS([\s\S]*?)(Homework Assignment:|$)/i);
        if (activitiesTextMatch) {
            const activitiesText = activitiesTextMatch[1];
            const activityRegex = /(ACTIVATING PRIOR KNOWLEDGE|ACQUIRING NEW KNOWLEDGE|APPLYING KNOWLEDGE|ASSESSMENT: ASSESSING KNOWLEDGE)\s*\((\d+)\s*mins?\)([\s\S]*?)(?=(?:ACTIVATING PRIOR KNOWLEDGE|ACQUIRING NEW KNOWLEDGE|APPLYING KNOWLEDGE|ASSESSMENT: ASSESSING KNOWLEDGE|Homework Assignment:|$))/gi;

            let match;
            while ((match = activityRegex.exec(activitiesText)) !== null) {
                const activity: Activity = {
                    name: match[1].trim(),
                    duration: parseInt(match[2], 10),
                    description: match[3].trim(),
                };
                lessonPlan.activities.push(activity);
                if (activity.name.includes('ASSESSMENT: ASSESSING KNOWLEDGE')) {
                    lessonPlan.assessment = activity.description;
                }
            }
        }
        
        const homeworkMatch = text.match(/Homework Assignment:([\s\S]*)/i);
        if (homeworkMatch) lessonPlan.homework = homeworkMatch[1].trim() || 'None';
        else lessonPlan.homework = 'None';
        
        lessonPlan.summary = `A 40-minute lesson plan for ${lessonPlan.gradeLevel} ${lessonPlan.subject} focusing on "${lessonPlan.title}". Key activities include activating prior knowledge, introducing new material, application-based practice, and a final assessment.`;

        if (!lessonPlan.title || lessonPlan.activities.length === 0) {
             throw new Error("Failed to parse key sections of the lesson plan.");
        }

        return lessonPlan;
    } catch (e) {
        console.error("Error parsing lesson plan text:", e);
        throw new Error("Failed to parse the lesson plan generated by the model. The format might be incorrect.");
    }
}


export async function generateLessonPlan(slo: SLO, unitSlos: SLO[]): Promise<LessonPlan> {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });

  if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable not set.");
  }

  let gradeLevelContext: string;
  const gradeNum = parseInt(slo.grade?.replace('Grade ', '') || '9', 10);

  if (gradeNum <= 10) {
    gradeLevelContext = `${slo.grade} (Foundational)`;
  } else {
    gradeLevelContext = `${slo.grade} (Advanced)`;
  }
  
  const systemInstruction = `You are an expert curriculum developer for ${gradeLevelContext} Physics. Your task is to generate a concise, printable, 40-minute lesson plan based *exclusively* on the provided Student Learning Outcome (SLO) and the context of other SLOs from the same unit.

**Critical Instructions:**
1.  **Deconstruct Topic & Pace:** Your most critical task is to analyze the user's requested SLO and the provided context SLOs to identify a focused, logical sub-topic suitable for a single 40-minute lesson. The lesson plan must NEVER cover an entire chapter or a broad topic. It must be granular and specific.
2.  **Strictly Grounded:** Base the entire lesson plan ONLY on the content of the provided SLOs. Do not use any external knowledge or information.
3.  **MANDATORY OUTPUT FORMAT:** The output must ONLY be the body of the lesson plan. The total duration of all activities must be exactly 40 minutes.
4.  **Grade Appropriateness:** All content, activities, and assessments must be appropriate for the specified grade level: ${gradeLevelContext}.

**Follow this exact structure and formatting:**

LESSON TOPIC: [A short, descriptive title for the specific sub-topic covered in this 40-minute lesson]

LEARNING OBJECTIVES (SLOs): (Students will be able to: *) [The learning objective, which should be a clear restatement of the user's provided SLO.]

RESOURCES:i.e
- [Whiteboard and markers]
- [Sindh Text book]

LESSON PROCEDURE & TIMINGS
ACTIVATING PRIOR KNOWLEDGE ([duration in minutes] mins)
[Detailed description of the activity]

ACQUIRING NEW KNOWLEDGE ([duration in minutes] mins)
[Detailed description of the activity]

APPLYING KNOWLEDGE ([duration in minutes] mins)
[Detailed description of the activity]

ASSESSING KNOWLEDGE ([duration in minutes] mins)
[Detailed description of the activity. This should also contain the assessment summary.]

`;
  const contextText = unitSlos
    .filter(s => s.uniqueId !== slo.uniqueId)
    .map(s => `- ${s.SLO_ID}: ${s.SLO_Text}`)
    .join('\n');

  const userPrompt = `Generate a lesson plan for the following SLO:
**${slo.SLO_ID}: ${slo.SLO_Text}**

For context, here are other SLOs from the same unit:
${contextText}
`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: { parts: [{ text: userPrompt }] },
      config: {
        systemInstruction: systemInstruction,
        temperature: 0.2,
      },
    });

    const lessonPlan = parseLessonPlanText(response.text, gradeLevelContext, 'Physics');
    
    return lessonPlan;
  } catch (error) {
    console.error("Error generating lesson plan:", error);
    if (error instanceof Error) {
        if (error.message.includes('429')) {
             throw new Error("API rate limit exceeded. Please try again later.");
        }
        if (error.message.includes('API key not valid')) {
            throw new Error("Invalid API Key. Please check your configuration.");
        }
        if (error.message.includes('Failed to parse')) {
            throw error;
        }
    }
    throw new Error("Failed to generate lesson plan. The model may have returned an unexpected response.");
  }
}
